import pandas as pd
from pathlib import Path
from src.utils.logger import setup_logging, get_logger
from src.utils.config import get_data_dir

setup_logging()
logger = get_logger("exp011a1_feasibility")

def run_feasibility_audit():
    logger.info("Starting EXP011A.1: Representation Feasibility Audit")
    
    # We will use the features generated by EXP011A to check sparsity
    # But since EXP011A didn't save the dataframe, we will quickly re-simulate
    # the stack depth for all gold quotes to see how sparse depth >= 3 is.
    
    from src.discourse.conversation_state import ConversationStateModule
    from src.features.conversation_extractor import ConversationFeatureExtractor
    
    input_file = get_data_dir() / "raw" / "pdnc" / "phase2" / "candidate_features.csv"
    if not input_file.exists():
        input_file = get_data_dir() / "phase2" / "candidate_features.csv"
        
    df = pd.read_csv(input_file)
    
    extractor = ConversationFeatureExtractor()
    depths = []
    
    # We only care about the gold speaker's depth, because that's the signal the model needs to learn
    gold_df = df[df['label'] == 1].copy()
    
    for novel, novel_df in df.groupby('novel'):
        state = ConversationStateModule(novel)
        unique_quotes = novel_df['quote_id'].unique()
        
        for q_id in unique_quotes:
            q_df = novel_df[novel_df['quote_id'] == q_id]
            
            gold_rows = q_df[q_df['label'] == 1]
            if len(gold_rows) > 0:
                gold_speaker = gold_rows.iloc[0]['candidate']
                
                # Check the depth BEFORE updating
                f = extractor.extract({}, gold_speaker, state)
                depth = f.get('candidate_stack_depth', 0.0)
                if f.get('candidate_in_participant_stack', 0.0) == 0.0:
                    depth = 0.0
                    
                depths.append({
                    'quote_id': q_id,
                    'gold_speaker': gold_speaker,
                    'stack_depth': depth
                })
            else:
                gold_speaker = "Unknown"
                
            if q_df.iloc[0]['discourse_dialogue_position'] == 1:
                state.reset(novel)
                
            state.update({}, gold_speaker)
            
    depth_df = pd.DataFrame(depths)
    
    # Quantify Sparsity
    total_quotes = len(depth_df)
    depth_counts = depth_df['stack_depth'].value_counts().sort_index()
    
    logger.info(f"Total Gold Quotes Evaluated: {total_quotes}")
    for d, count in depth_counts.items():
        pct = (count / total_quotes) * 100
        logger.info(f"Depth {int(d)}: {count} quotes ({pct:.2f}%)")
        
    depth_3_plus = depth_df[depth_df['stack_depth'] >= 3]
    pct_3_plus = (len(depth_3_plus) / total_quotes) * 100
    logger.info(f"Overall Depth >= 3: {len(depth_3_plus)} quotes ({pct_3_plus:.2f}%)")
    
    # Check against Speaker Continuity failures
    exp010_file = Path("results") / "EXP010" / "semantic_annotations_master.csv"
    if exp010_file.exists():
        exp010_df = pd.read_csv(exp010_file)
        if 'Quote_ID' in exp010_df.columns:
            exp010_df = exp010_df.rename(columns={'Quote_ID': 'quote_id'})
            
        spk_cont = exp010_df[exp010_df['ANNOTATION: Primary Category'] == 'Discourse: Speaker Continuity']
        merged = spk_cont.merge(depth_df, on='quote_id', how='inner')
        
        sc_total = len(merged)
        sc_depth_3 = len(merged[merged['stack_depth'] >= 3])
        sc_pct = (sc_depth_3 / sc_total) * 100 if sc_total > 0 else 0
        
        logger.info(f"Speaker Continuity Failures with Depth >= 3: {sc_depth_3} / {sc_total} ({sc_pct:.2f}%)")

if __name__ == "__main__":
    run_feasibility_audit()
